# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: dd193a9da77e37e3e3fec02459e06f805bb0f6eb4a56b5cdee96330df1c6c1ead23570fa055e483c2456f8895c94a0a658377cfe13c34f645dbabcc47cfe4360

test:
  secret_key_base: 8ce7afbc57f762f824a1d8ac4bf2c0aac3e66cf4ba13b23116736efe5a4441822deb85384069b944111dc19e0cd4d6fec0e573b0c7c44374eb38ef1690b8f76d

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
